apotik/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
] 

main/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path("login/", views.user_login, name="login"),
    path('logout/', views.user_logout, name='logout'),
    path('obat/', views.obat, name='obat'),
    path('tambah_obat/', views.addObat, name='tambah_obat'),
    path('edit_obat/<str:pk>/', views.updateObat, name='edit_obat' ),
    path('hapus_obat/<str:pk>/', views.deletObat, name='hapus_obat'),
    path('pelanggan/', views.custemer, name='pelanggan'),
    path('tambah_pelanggan/', views.addCustemer, name='tambah_pelanggan'),
    path('edit_pelanggan/<str:pk>/', views.updateCustemer, name='edit_pelanggan'),
    path('hapus_pelanggan/<str:pk>/', views.deletCustemer, name='hapus_pelanggan'),
    path('transaksi/', views.order, name='transaksi'),
    path('tambah_transaksi/', views.addOrder, name='tambah_transaksi'),
    path('user/', views.user, name="user"),
    path('tambah_user/', views.addUser, name="tambah_user"),
    
]

main/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Profile(models.Model):
    
    ROLE_CHOICES = (
        ('Admin','Admin'),       
        ('User','User'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    role = models.CharField(max_length=50, choices=ROLE_CHOICES)
    def __str__(self):
        return self.user.username
    
    
class Custemer(models.Model):
    kode_custemer = models.CharField(max_length=50, blank=True, null=True)
    name_custemer = models.CharField(max_length=50, blank=True, null=True)
    email_custemer = models.EmailField(max_length=254, blank=True, null=True)
    telpon_custemer = models.CharField(max_length=50, blank=True, null=True)
    alamat_custemer = models.TextField()
    
    def __str__(self):
        return self.name_custemer
class Obat(models.Model):
    kode_obat = models.CharField(max_length=50)
    name_obat = models.CharField(max_length=50)
    price_obat = models.IntegerField(blank=True, null=True)
    stok_obat = models.IntegerField(blank=True, null=True)
    description = models.TextField()
    date_created = models.DateTimeField(auto_now_add=False, null=True)
    
    def __str__(self):
        return self.name_obat
    
class Order(models.Model):
    obat_id = models.ForeignKey(Obat, null=True, on_delete=models.SET_NULL)
    custemer_id = models.ForeignKey(Custemer, null=True, on_delete=models.SET_NULL)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    qty_order = models.IntegerField(blank=True, null=True)
    qty_price = models.IntegerField(blank=True,null=True)
    discon = models.IntegerField(blank=True, null=True)
    price_after_disc = models.IntegerField(blank=True, null=True)
    
    def __str__(self):
        return self.obat_id.name_obat
    
   

templates/index/index.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}

  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <link rel="icon" href="{% static '/img/obat.png' %}" />

    <title>apotik</title>

    <!-- Custom fonts for this template-->
    <link
      href="{% static '/vendor/fontawesome-free/css/all.min.css' %}"
      rel="stylesheet"
      type="text/css"
    />

    <!-- stnk css-->
    <link
      href="{% static '/stnk/css/index.css' %}"
      rel="stylesheet"
      type="text/css"
    />

    <link
      href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
      rel="stylesheet"
    />
    <!-- jqueury template-->
    <link
      href="{% static '/js/jquery-ui-1.12.1/jquery-ui.min.css' %}"
      rel="stylesheet"
      type="text/css"
    />

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css"
      integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y="
      crossorigin="anonymous"
    />

    <!-- Custom styles for this template-->
    <link href="{% static '/css/sb-admin-2.min.css'%}" rel="stylesheet" />

    <!-- Custom styles for this page -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      href="{% static '/vendor/datatables/dataTables.bootstrap4.min.css' %}"
      rel="stylesheet"
    />
  </head>

  <body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">
      <!-- Sidebar -->
      <ul
        class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion"
        id="accordionSidebar"
      >
        <!-- Sidebar - Brand -->
        <a
          class="sidebar-brand d-flex align-items-center justify-content-center"
          href="#"
        >
          <div class="">
            <img class="img" src="{% static 'img/obat.png' %}" width="40px" />
          </div>
          <div class="sidebar-brand-text mx-3">apotik</div>
        </a>

        <!-- Divider -->
        <hr class="sidebar-divider" />

        <!-- Heading -->

        <!-- Nav Item - Dashboard -->
        <li class="nav-item">
          <a class="nav-link" class="selected" href="{% url 'home' %}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span></a
          >
        </li>
        {% if request.user.profile.role == 'Admin' %}
        <!-- Divider -->
        <hr class="sidebar-divider" />
        <div class="sidebar-heading">Administrator</div>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'user' %}">
            <i class="fas fa-fw fa-hospital-user"></i>
            <span>User</span></a
          >
        </li>
        {% endif %}
        <!-- Divider -->
        <hr class="sidebar-divider" />

        <!-- Heading -->
        <div class="sidebar-heading">User</div>
        <!-- Nav Item - Charts -->
        <li class="nav-item">
          <a class="nav-link" href="{% url 'obat' %}">
            <i class="fas fa-fw fa-medkit"></i>
            <span>Obat</span></a
          >
        </li>
        <!-- Nav Item - Charts -->
        <li class="nav-item">
          <a class="nav-link" href="{% url 'pelanggan' %}">
            <i class="fas fa-fw fa-user-alt"></i>
            <span>Pelanggan</span></a
          >
        </li>

        <!-- Nav Item - Charts -->
        <li class="nav-item">
          <a class="nav-link" href="{% url 'transaksi' %}">
            <i class="fas fa-fw fa-cart-plus"></i>
            <span>Transaksi</span></a
          >
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider" />

        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">
            <i class="fas fa-fw fa-sign-out-alt"></i>
            <span>Keluar</span></a
          >
        </li>
        <!-- Divider -->
        <hr class="sidebar-divider d-none d-md-block" />

        <!-- Sidebar Toggler (Sidebar) -->
        <div class="text-center d-none d-md-inline">
          <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div>
      </ul>
      <!-- End of Sidebar -->

      <!-- Content Wrapper -->
      <div id="content-wrapper" class="d-flex flex-column">
        <!-- Main Content -->
        <div id="content">
          <!-- Topbar -->
          <nav
            class="
              navbar navbar-expand navbar-light
              bg-white
              topbar
              mb-4
              static-top
              shadow
            "
          >
            {% comment %}
            <!-- Sidebar Toggle (Topbar) -->
            <button
              id="sidebarToggleTop"
              class="btn btn-link d-md-none rounded-circle mr-3"
            >
              <i class="fa fa-bars"></i>
            </button>

            <form
              class="
                d-none d-sm-inline-block
                form-inline
                mr-auto
                ml-md-3
                my-2 my-md-0
                mw-100
                navbar-search
              "
              method="post"
              action=""
            >
              <div class="input-group">
                <input
                  type="text"
                  name="keyword"
                  class="form-control bg-light border-0 small"
                  placeholder="Search for..."
                  autocomplete="off"
                />
                <div class="input-group-append">
                  <button class="btn btn-success" type="submit">
                    <i class="fas fa-search fa-sm"></i>
                  </button>
                </div>
              </div>
            </form>
            {% endcomment %}

            <!-- Topbar Navbar -->
            <ul class="navbar-nav ml-auto">
              <!-- Nav Item - User Information -->
              <li class="nav-item dropdown no-arrow">
                <a
                  class="nav-link dropdown-toggle"
                  href="#"
                  id="userDropdown"
                  role="button"
                  data-toggle="dropdown"
                  aria-haspopup="true"
                  aria-expanded="false"
                >
                  <span class="mr-2 d-none d-lg-inline text-gray-600 small">
                    {% if user.is_authenticated %}
                    <strong>{{user}}</strong>

                    {% endif %}
                  </span>

                  <img
                    class="img-profile rounded-circle"
                    src="{% static 'img/profile/default.png' %}"
                  />
                </a>
                <!-- Dropdown - User Information -->
                <div
                  class="
                    dropdown-menu dropdown-menu-right
                    shadow
                    animated--grow-in
                  "
                  aria-labelledby="userDropdown"
                >
                  <a class="dropdown-item" href="#">
                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                    Profile
                  </a>
                  <a class="dropdown-item" href="#">
                    <i class="fas fa-fw fa-key mr-2 text-gray-400"></i>
                    Ganti Password
                  </a>
                  <a
                    class="dropdown-item"
                    href="{% url 'logout' %}"
                    data-toggle="modal"
                    data-target="#logoutModal"
                  >
                    <i
                      class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"
                    ></i>
                    Keluar
                  </a>
                </div>
              </li>
            </ul>
          </nav>
          <!-- End of Topbar -->

          {% block content %} {% endblock %}
        </div>
        <!-- End of Main Content -->

        <!-- Footer -->
        <footer class="sticky-footer bg-white">
          <div class="container my-auto">
            <div class="copyright text-center my-auto">
              <span>Copyright &copy; @isaasrori 2021</span>
            </div>
          </div>
        </footer>
        <!-- End of Footer -->
      </div>
      <!-- End of Content Wrapper -->
    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div
      class="modal fade"
      id="logoutModal"
      tabindex="-1"
      role="dialog"
      aria-labelledby="exampleModalLabel"
      aria-hidden="true"
    >
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">
              Siap Untuk Keluar?
            </h5>
            <button
              class="close"
              type="button"
              data-dismiss="modal"
              aria-label="Close"
            >
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">
            Pilih "Keluar" di bawah jika kamu ingin keluar dan perkerjan anda
            sudah selesai.
          </div>
          <div class="modal-footer">
            <button
              class="btn btn-secondary"
              type="button"
              data-dismiss="modal"
            >
              Batal
            </button>
            <a class="btn btn-primary" href="{% url 'logout' %}">Keluar</a>
          </div>
        </div>
      </div>
    </div>

    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="{% static '/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static '/js/jquery-ui-1.12.1/jquery-ui.min.js' %}"></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js"
      integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk="
      crossorigin="anonymous"
    ></script>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static '/vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static '/vendor/jquery-easing/jquery.easing.min.js'%}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static '/js/sb-admin-2.min.js'%}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %} "></script>

    <!-- Page level custom scripts -->
    <script src=" {% static 'js/demo/datatables-demo.js' %}"></script>
    <!-- block script JavaScript -->
    <script src=" {% static 'vendor/chart.js/Chart.min.js' %}"></script>
    <script src=" {% static 'js/demo/chart-area-demo.js' %}"></script>
    <script src=" {% static 'js/demo/chart-pie-demo.js' %}"></script>

    <script>
      $(function () {
        $("#id_date_created").datetimepicker({
          format: "Y-m-d H:i",
        });
      });

      $("#perhitungan").keyup(function () {
        var price = parseInt($("#price_obat").val());
        var qtyOrder = parseInt($("#qty_order").val());

        var qtyPrice = price * qtyOrder;

        $("#qty_price").attr("value", qtyPrice);
      });
    </script>
  </body>
</html>